In [48]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [49]:
data2=pd.read_csv('clean_car_data.csv')

In [50]:
data2.head()

,Brand,fueltype,symboling,doornumber,carbody,drivewheel,cylindernumber,enginesize,horsepower,price
0,alfa-romeo,gas,3,two,convertible,rwd,4,130,111,13495.0
1,alfa-romeo,gas,3,two,convertible,rwd,4,130,111,16500.0
2,alfa-romeo,gas,1,two,hatchback,rwd,6,152,154,16500.0
3,audi,gas,2,four,sedan,fwd,4,109,102,13950.0
4,audi,gas,2,four,sedan,4wd,5,136,115,17450.0

In [51]:
X = data2.drop('price', axis=1)
y= data2['price']

In [52]:
X.head()

,Brand,fueltype,symboling,doornumber,carbody,drivewheel,cylindernumber,enginesize,horsepower
0,alfa-romeo,gas,3,two,convertible,rwd,4,130,111
1,alfa-romeo,gas,3,two,convertible,rwd,4,130,111
2,alfa-romeo,gas,1,two,hatchback,rwd,6,152,154
3,audi,gas,2,four,sedan,fwd,4,109,102
4,audi,gas,2,four,sedan,4wd,5,136,115

In [53]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [54]:
 categorical = ['Brand', 'fueltype', 'doornumber', 'carbody', 'drivewheel']

In [55]:
preprocessor = ColumnTransformer(transformers=[('cat', OneHotEncoder(handle_unknown='ignore'), categorical)], remainder='passthrough')

In [56]:
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

In [57]:
print('Training shape is', X_train_transformed.shape)
print('Testing shape is', X_test_transformed.shape)

Training shape is (163, 38)
Testing shape is (41, 38)

In [58]:
model = LinearRegression()
model.fit(X_train_transformed, y_train)

LinearRegression()

In [59]:
y_pred = model.predict(X_test_transformed)

In [60]:
MAE=mean_absolute_error(y_pred, y_test)
MSE=mean_squared_error(y_pred,y_test)
RScore=r2_score(y_pred, y_test)

In [67]:
print('Mean Absolute Error is: ', MAE)
print('Mean Squared Error is: ', MSE)
print('R Squared score is: ', RScore)

Mean Absolute Error is:  2379.821410673599
Mean Squared Error is:  12273132.200541647
R Squared score is:  0.8706985097875404

In [68]:
coeficient = model.coef_
feature_names = preprocessor.get_feature_names_out()

In [69]:
data3=pd.DataFrame({'feature':feature_names, 'coeficient':coeficient})
data3

                      feature    coeficient
0       cat__Brand_alfa-romeo  -1669.012597
1             cat__Brand_audi   2928.458651
2              cat__Brand_bmw   6771.091949
3            cat__Brand_buick  14178.953479
4        cat__Brand_chevrolet  -3131.213492
5            cat__Brand_dodge  -3528.706893
6            cat__Brand_honda  -2536.543730
7            cat__Brand_isuzu  -1914.675149
8           cat__Brand_jaguar   7855.315544
9            cat__Brand_mazda  -2002.754292
10         cat__Brand_mercury  -3361.353784
11      cat__Brand_mitsubishi  -4335.709482
12          cat__Brand_nissan  -3093.250447
13         cat__Brand_peugeot    419.617836
14        cat__Brand_plymouth  -3770.855178
15         cat__Brand_porsche   8770.530119
16         cat__Brand_renault  -3353.746609
17            cat__Brand_saab    -18.858065
18          cat__Brand_subaru  -3814.203775
19          cat__Brand_toyota  -3134.432351
20      cat__Brand_volkswagen  -2395.683326
21           cat__Brand_volvo   1137.031592
22       cat__fueltype_diesel    788.010822
23          cat__fueltype_gas   -788.010822
24       cat__doornumber_four    553.866215
25        cat__doornumber_two   -553.866215
26   cat__carbody_convertible   2060.574813
27       cat__carbody_hardtop    143.790222
28     cat__carbody_hatchback   -415.325038
29         cat__carbody_sedan   -795.427135
30         cat__carbody_wagon   -993.612862
31        cat__drivewheel_4wd    817.123710
32        cat__drivewheel_fwd   -409.409916
33        cat__drivewheel_rwd   -407.713794
34       remainder__symboling     64.424750
35  remainder__cylindernumber   -490.673683
36      remainder__enginesize     43.831797
37      remainder__horsepower     80.329662