### importing necessary libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import joblib

### loading the dataset into jupyter notebook

In [2]:
data2=pd.read_csv('clean_car_data.csv')

###Displaying the first 5 rows

In [3]:
data2.head()

,Brand,fueltype,symboling,doornumber,carbody,drivewheel,cylindernumber,enginesize,horsepower,price
0,alfa-romeo,gas,3,two,convertible,rwd,4,130,111,13495.0
1,alfa-romeo,gas,3,two,convertible,rwd,4,130,111,16500.0
2,alfa-romeo,gas,1,two,hatchback,rwd,6,152,154,16500.0
3,audi,gas,2,four,sedan,fwd,4,109,102,13950.0
4,audi,gas,2,four,sedan,4wd,5,136,115,17450.0

In [4]:
###X = data2.drop('price', axis=1) — Removes the price column and stores the remaining features in X.
###y = data2['price'] — Selects the price column as the target variable and stores it in y.

In [5]:
X = data2.drop('price', axis=1)
y= data2['price']

In [6]:
###x.head() — Displays the first five rows of the dataset X to quickly inspect the feature data.

In [7]:
X.head()

,Brand,fueltype,symboling,doornumber,carbody,drivewheel,cylindernumber,enginesize,horsepower
0,alfa-romeo,gas,3,two,convertible,rwd,4,130,111
1,alfa-romeo,gas,3,two,convertible,rwd,4,130,111
2,alfa-romeo,gas,1,two,hatchback,rwd,6,152,154
3,audi,gas,2,four,sedan,fwd,4,109,102
4,audi,gas,2,four,sedan,4wd,5,136,115

In [8]:
###spliting the data into traing and testing data

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
###Define a list of categorical variables in the dataset. These variables contain non-numerical categories that may need to be encoded before training

In [11]:
categorical = ['Brand', 'fueltype', 'doornumber', 'carbody', 'drivewheel']

In [12]:
##preprocessor = ColumnTransformer(...) — Creates a preprocessing step that transforms the categorical variables into numerical form using One-Hot Encoding.
##handle_unknown='ignore' — Ensures new or unseen categories do not cause errors, while remainder='passthrough' keeps the numerical variables unchanged.

In [13]:
preprocessor = ColumnTransformer(transformers=[('cat', OneHotEncoder(handle_unknown='ignore'), categorical)], remainder='passthrough')

In [14]:
###X_train_transformed = preprocessor.fit_transform(X_train) — Fits the preprocessor on the training data and transforms it into a numerical format.
###X_test_transformed = preprocessor.transform(X_test) — Applies the same preprocessing to the test data without refitting the preprocessor.

In [15]:
X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.transform(X_test)

In [16]:
print('Training shape is', X_train_transformed.shape)
print('Testing shape is', X_test_transformed.shape)

Training shape is (163, 38)
Testing shape is (41, 38)

In [17]:
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train_transformed, y_train)

RandomForestRegressor(random_state=42)

In [18]:
y_pred = model.predict(X_test_transformed)

In [19]:
MAE=mean_absolute_error(y_pred, y_test)
MSE=mean_squared_error(y_pred,y_test)
RScore=r2_score(y_pred, y_test)

In [20]:
print('Mean Absolute Error is: ', MAE)
print('Mean Squared Error is: ', MSE)
print('R Squared score is: ', RScore)

Mean Absolute Error is:  1943.1951631823463
Mean Squared Error is:  7635113.383479574
R Squared score is:  0.8955406180775288

In [21]:
importances = model.feature_importances_
feature_names = preprocessor.get_feature_names_out()

##This code creates a Pandas DataFrame called data3 that stores the features and their corresponding importance values

In [22]:
data3=pd.DataFrame({'feature':feature_names, 'importances':importances})
data3

                      feature  importances
0       cat__Brand_alfa-romeo     0.000148
1             cat__Brand_audi     0.002045
2              cat__Brand_bmw     0.007389
3            cat__Brand_buick     0.005801
4        cat__Brand_chevrolet     0.000018
5            cat__Brand_dodge     0.000301
6            cat__Brand_honda     0.000512
7            cat__Brand_isuzu     0.000281
8           cat__Brand_jaguar     0.000687
9            cat__Brand_mazda     0.000824
10         cat__Brand_mercury     0.000106
11      cat__Brand_mitsubishi     0.000848
12          cat__Brand_nissan     0.000716
13         cat__Brand_peugeot     0.001369
14        cat__Brand_plymouth     0.000227
15         cat__Brand_porsche     0.000008
16         cat__Brand_renault     0.000457
17            cat__Brand_saab     0.000477
18          cat__Brand_subaru     0.000115
19          cat__Brand_toyota     0.004693
20      cat__Brand_volkswagen     0.001171
21           cat__Brand_volvo     0.001930
22       cat__fueltype_diesel     0.000418
23          cat__fueltype_gas     0.000474
24       cat__doornumber_four     0.001679
25        cat__doornumber_two     0.001345
26   cat__carbody_convertible     0.001835
27       cat__carbody_hardtop     0.003027
28     cat__carbody_hatchback     0.003303
29         cat__carbody_sedan     0.004551
30         cat__carbody_wagon     0.001097
31        cat__drivewheel_4wd     0.000258
32        cat__drivewheel_fwd     0.003105
33        cat__drivewheel_rwd     0.003553
34       remainder__symboling     0.010053
35  remainder__cylindernumber     0.023098
36      remainder__enginesize     0.711909
37      remainder__horsepower     0.200172

In [23]:
joblib.dump(model, 'model.joblib')

['model.joblib']

In [24]:
joblib.dump(preprocessor, 'preprocessor.joblib')

['preprocessor.joblib']